# Answers for Essay 1

***Critical Reflection 1 & 2 (160 points):*** Each reflective analysis is worth a possible total of 20 points per category, times 4 categories equals 80 points times 2 reflection pieces.

You will be required to write one paper, which must be type-written, double-spaced, and six to eight pages in length. This is NOT a research paper. Below are several topics, each student must choose ONE to which s/he will respond. If you wish to write a paper on a topic other than one of those suggested by me contact me after class and we can make an appointment during my office hours to discuss other topics. (I will be more than happy to approve relevant topics.) The papers you write are not opinion papers. It is standard practice among philosophers to view mere opinion to be worth less than the energy used to express it. What is worthwhile is a reasoned defense of one’s opinion. Your paper should be written so as to present rational argument for the position which you hold.

Your paper should consist of two distinct parts. The first part, which should account for approximately half the length of the paper, should be a short explication of the essay you have chosen. This part should contain a statement of the author’s position, a statement of your own position (tell me whether you agree or disagree with the author) and an explanation of the author’s supporting arguments. The second half of the paper should consist of your own evaluation or critique of the essay. In this part of the paper you should tell me WHY you agree or disagree with the author. If you agree with the author you should tell me what argument(s) are convincing. Then tell me what argument(s) might be pro↵ered by one who disagrees with the author and how the author might respond. If you disagree with the author, you should provide criticism of the author’s essay and attempt to explain how the author might respond to the criticism. Hence, whether you agree or disagree with the author, you should provide arguments against the author and responses thereto. Finally, you should explain why you believe your position is the best position. You must NOT use outside sources for this essay. I will provide a more detailed account in class.

Chalmers quotes *Ready Player One*: "Reality is the only thing that's real." His own view however does not deviate from this idea.

Chalmer's View:

1. Virtual Realism
2. Simulation Realism
3. Virtual Digitalism

Explain the view that Chalmer's defends highlighting the three views on realism he accepts.

Defining *Real*:

Chalmers accepts three meanings of *real*, these include

1. Existence
2. World as an interconnected physical or virtual space
3. The rigidity of properties

Additionally, explain the relationship between these views and his five ways of "thinking about what's real".

* Reality as existence
* Reality as causal power
* Reality as mind-independence
* Reality as non-illusoriness
* Reality as genuineness

The above constitute five questions to ask when wondering if something is real.

It is either one of the above or a mix of them. Chalmers accepts all five of the criteria:

1. Simulation Realism:
   1. Fundamentalism $\lor$ Originality are marginal issues (Dolly the cloned sheep is non-original yet real).
   2. Beliefs about digital natures are largely scientific or philosophical, but do not undermine everyday beliefs.
   3. Therefore beliefs about experience in a simulation will be right.
2. Virtual Realism:
   1. Its from bits hypothesis
   2. Creation hypothesis

Molecules $\rightarrow$ atoms $\rightarrow$ quarks $\rightarrow$ bits. Bits are underlying layers of reality we don't yet know about. Therefore simulation hypothesis is a metaphysical one.


