## Course Description

We will examine theories which attempt to provide answers to such questions as: What is a law? What makes a law valid or binding? Does one always have a moral obligation to obey the law? What gives society the right to punish people whose actions are harmful only to the individual, him/herself (paternalism)? Does society have the right to harm those who break the law (criminal punishment)? Should attempted crimes be punished less severely than completed crimes? We will not spend much time discussing specific public policy issues such as: Whether raising the drinking age saves lives, whether smoking marijuana is a victimless crime (whether it harms others), or whether the death penalty is a deterrent. We will not discuss what the law is; instead, we will discuss what the law ought to be.

### 📑 Course Brief {width="50%"}

**Focus:**

1. Developing critical reasoning skills.
2. Discovering some of the fundamental philosophical ideas in law.

**Text:** Feinberg, Joel, and Jules L. Coleman. 2008. Philosophy of Law / [Edited by] Joel Feinberg, Jules Coleman. 8th ed. Thomson/Wadsworth.

🎯 Learning Objectives

* What is a law?
* What makes a law valid or binding?
* Do we have a moral obligation to obey the law?
* What gives society the right to punish people whose actions are harmful only to the individual, him/herself (paternalism)?
* Does society have the right to harm those who break the law (criminal punishment)?
* Should attempted crimes be punished less severely than completed crimes?

What is not covered

Public policy issues such as:

* Whether raising the drinking age saves lives
* Wehther smoking marijuana is a victimless crime (whether it harms others)
* Whether the death penalty is a deterrent.

We do not discuss what the law is; instead, we will discuss what the law ought to be.

## The Speluncean Explorers {with="50%"}

***The Speluncean Explorers***

<iframe width="560" height="315" src="https://www.youtube.com/embed/GOZrKgIMtWo?si=ApOqwLPMkpgl-Brx&amp;controls=0&amp;start=7890" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
