---
subtitle: "The Case of the Speluncean Explorers, Fuller"
title: "<font style='font-size:1em;'>🗓️ Week 02<br/> Natural Law</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Five Theories of Law"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL104Q -- Introduction to Logic'
---

# What is Law?

Jurisprudence is a theory about the ontological nature of law.

---

* How do we answer this question?
  * With a Definition?
  * A Description of the word law?
  * A historical analysis of the ways in which this term was used?

---

* Is it a set of practices?
  * Which ones count as law?
  * Who decides?
  * Who's practices count?

## Overview

::: {.notes}

- Setting: Court of Law, year 4299
- Theme: The Speluncean explorers have been tried for the murder of Roger Whetmore and found guilty. Five chief justices give their opinions on the case and whether or not the judgment is just.
- Hook: Two points of interest, the opinions of the justices and the justification they use in this opinion.

:::

## Background

::: {.notes}
- Key history: The explorers were all members of the Speluncean explorer society. They were trapped during one of their expeditions by large boulders blocking their exit from a cave they were exploring. Initially the explorers had been in contact with the outside world and their potential rescurers. However, this communication had become disrupted shortly after bein informed that it was likely they would die of starvation before their rescue. Upon their eventual rescue, it was learned that this party had survived, possibly because of the murder and cannibilization of one of their members, Mr. Roger Whetmore. Further it was learned that it was initially Whetmore's idea that they pick lots to decide whose flesh should serve as sustinance for the remaining members, although shortly before lots were drawn, Whetmore had withdrawn his support from this idea implying that he did not consent to this arrangement. His lot in turn, was cast for him.

- Important factions: Truepenny, Foster, Tatting, Keen, Handy.

:::

## Major conflicts

::: {.r-fit-text}

Natural Law

Legal Positivism

Legal Realism and Scepticism

Interpretationist theories

When trying to develop a theory of law:

* Obligation is important
* Normativity, when deciding what to do, we ask "what counts", or what is "entitled" to count.
* Law == criteria of right judgment in conduct, action
* Acts as a standard for human conduct: enables judgments such as good; bad, right; wrong; desirable; undesirable; decent or unworth.

:::

---

<style>
.container{
  display: flex;
}
.col {
  flex: 1;
}
</style>

::: {.container}

:::: {.col}

Truepenny, CJ

Foster, J

::::

:::: {.col}

Keen, J.

Handy, J.

Tatting, J.

::::

:::

---

::: {.notes}

Concerning the normative account, when we speak of normativity, we will ask whether there are behaviors that are normative prior to our choices.

:::

## Truepenny, CJ

Is in favor of the court's decision. Ruling of the court should be upheld, namely against murder, while clemency should be offered to the defendants recognizing the extreme circumstances and choices they were faced with.

- But distinguishes between spirit and letter of the law. Letter: "Whoever shall willfully take the life of another shall be punished by death." Spirit?

---

One thing we are talking about then is obligation, or normativity. Does the law give us reason to perform, or refrain from performing a given action? Does the law count as a measure for assessing whether an action was good, bad, desirable, unworthy, right, wrong?

---

## Foster, J

> For us to assert that the law we uphold and expound compels us to a conclusion we are ashamed of, and from  which we can only escape by appealing to a dispensation resting within the personal whim of the Executive, seems to me to  amount to an admission that the law of this Commonwealth no longer pretends to incorporate justice. [@full49, 620]

---

- How? Law is grounded in spirit, "possibility of men's coexistence in society". When possibility is impossible, then positive law is no longer applicable.

---

> When the assumption that men live together loses its truth, as it obviously did in this extraordinary situation where life only became possible by the taking of a life, then the basic principles underlying our whole legal order have lost their meaning and force. [@full49, 621]

---

* We do not generally enforce our own laws outside of our geographical boundaries.

---

Consider two important distinctions: Established law, principles grounding established law.

* Law is grounded in contracts and agreements.
* Ancient: Original contract
* Skeptics: However, there is no evidence to support the claim that law is settled agreement.
* Moralists: However, if there is no evidence, then there is no evidence justifying the powers of government including the taking of lives.

---

Instead however, there is an original charter and all settled law points 'back' to it.

> We know as a matter of historical truth that our government was founded upon a contract or free accord of men.  The archaeological proof is conclusive that in the first period following the Great Spiral the survivors of that holocaust voluntarily came together and drew up a charter of government. Sophistical writers have raised questions as to the power of those remote contractors to bind future generations, but the fact remains that our government traces itself back in an unbroken line to that original charter. [@full49, 622]

## Rule of Law Argument

1. Governments have certain powers.
2. These powers are grounded in the original compact: agreement to ensure the possibility of coexistence.
3. If there is no precedent available to ensure peaceful cooperation, then the original contract is impossible.
4. When the original contract is impossible, then governmental powers are not justified.
5. The original contract is impossible.
6. Therefore current laws are not applicable.
7. As such, defendants are innocent.

## Rule of Law Counter Argument

1. Governments have certain powers.
2. These powers are grounded in the original compact: agreement to ensure the possibility of coexistence.
3. If there is no precedent available to ensure peaceful cooperation, then the original contract is impossible.
4. When the original contract is impossible, then governmental powers are not justified.
5. [counter] original contract is possible.
6. Self-defense example:

---

> When the rationale of the excuse of self-defense is thus explained, it becomes apparent that precisely the same reasoning is
applicable to the case at bar. If in the future any group of men
ever find themselves in the tragic predicament of these defendants,
we may be sure that their decision whether to live or die will not
be controlled by the contents of our criminal code. [@full49, 625]

---

7. Law would be ignored leading to impossibility of peaceful coexistence.
8. Therefore current laws are not applicable.
9. Defendants are innocent.

## Keen, J.

## Handy, J.

## Tatting, J.

#### Counter to State of Nature / Rule of Law Argument

1. The defendants were merely protecting their own lives.
2. In a state of nature, this is a justified and legal action.
3. Therefore, Whetmore with a revolver protecting his own life is unjustified killing (murder).
4. 2 and 3 == contradiction.
5. Argument from state of nature is a contradiction.

## Counter to Counter Argument

1. Law ensures peaceful cooperation.
2. When peaceful cooperation is impossible, then no law is justified.

---

Why?

---

1. Laws have purposes, positive effect and negative effect.
  1. Positive effect, ensure peaceful cooperation
  2. Negative effect, self-defense
