### Reading Schedule

***Adjust all dates by one for Tuesday Thursday Course***

***Weeklies Due Every Monday Starting Jan 19***

Wed Jan 14, handouts

Mon Jan 19 MLK Day, no classes

Wed Jan 21, Chapter 2, Simulation Hypothesis

Mon Jan 26, Chapter 3, Knowledge

Wed Jan 28, The external world, ch. 4

Mon Feb 2, ch. 5, Possible realities, bostrom and Moravec

Wed Feb 4, ch. 6, What is Reality?

Mon Fed 9, ch. 7, Is God a hacker in the universe up?

Wed Fed 11, ch. 8 Information, 2nd DND Adventure, Student Led

Mon Feb 16, ch. 9, On Bits

Wed Feb 18, ch. 10, Reality and Virtual Reality

Mon Feb 23, ch. 11, Illusion Machines

Wed Feb 25, Quiz 1

Mon Mar 02, Spring Break

Wed Mar 4, Spring Break

Mon Mar 9, ch. 13 ch. 12, 3rd DND Adventure, Student Led

Wed Mar 11, ch. 14, Mind and body Realism inside a virtual universe

Mon Mar 16, ch. 15, 4th DND Adventure, Student Led

Wed Mar 18, ch. 16, The extended mind hypothsis

Mon Mar 23, ch. 17 Critical Reflection Due

Wed Mar 25, ch. 18, Virtual ethics and intentiality

Mon Mar 30, ch. 19, Social Ontology inside virtual worlds

Wed Apr 1, ch. 20, 5th DND Adventure on Sense and Reference, Student Led

Mon Apr 6, ch. 21, Cause and effect inside virtual systems

Wed Apr 8, ch. 22, Mathematical, physical and cultural structualism

Mon Apr 13, ch. 23, Virtual Eden?

Wed Apr 15, ch. 24, Brains in a Vat

Mon Apr 20, TBD

Wed Apr 22, TBD

Mon Apr 27, TBD

Wed Apr 29, last day of classes, Final Quiz

Paper Due on Day of Final Quiz (Submit on Canvas)
