# CLS

Scholars try to establish the illegitimacy of the legal order by debunking law's pretensions to determinacy, neutrality, and objectivity.

Shaped by:

* Marxist
* Realist tradition
* Deconstruction
* Feminism
* Environmentalism
* Anti-racism

---

::: {.r-fit-text}

The central attack of CLS is formalism:

> "the idea that there is an autonomous and neutral mode of 'legal' reasoning and rationality through which legal specialists apply doctrine in concrete cases to reach results that are independent of the specialists' ethical ideals and political purposes." [J. Paul Oetken: Form and Substance in Critical Legal Studies, p. 2211]

Cls argues that instead law is indeterminate:  legal rules and arguments fail to compel or justify definite answers in legal disputes.

> A primary concern of CLS is to demonstrate how language and other formal structures are used in subtle, unconscious ways to channel our thought into dominant patterns, to mystify us. [J. Paul Oetken: Form and Substance in Critical Legal Studies, p. 2213]

:::

---

# Rhetorical Modes and Substantive Issues in the Law

What is the nature and interconnection of the different rhetorical modes found in American private law opinions, articles, and treatises?

* Formal dimensions of rules and standards
* Substantive dimensions of individualism and altruism

## Two modes for dealing with questions of the form in which legal solutions to the substantive problems:

* Formal Rules: uses clearly defined, highly administrable, general rules
* Informal Standards: uses equitable standards that produce ad hoc decisions with little precedential (precedent) value.

---

::: {.r-fit-text}

As Such:

1. Altruist views on substantive private law issues lead to willingness to resort to standards in administration.
2. Individualism harmonizes with an insistence on rigid rules rigidly applied (formal modes).
3. Substantive and formal conflict in private law and cannot be reduced to disagreement about how to apply some neutral calculus that will "maximize the total satisfactions of valid human wants".
4. Therefore, we are divided among ourselves and also within ourselves between irreconcilable visions of humanity and society, and between radically different aspirations for our common future.

:::

---

### Sections I and II

::: {.r-fit-text}

1. Jurisprudence of Rules
   1. Dimensions of Form
   2. Relationships between formal dimensions
2. Types of relationships between form and substance
   1. Contextualization
   2. Form as Substance
   3. Altruism and Individualism
* Problem of choice between rules and standards as the form for legal directives.
* Collecting and organizing the wide variety of arguments that have been found persuasive in different areas of legal study.

:::

---

### Sections III and IV

* Develops a dichotomy of individualism and altruism
* Hopes to bring a measure of order to the chaotic mass of "policies" lawyers
* Policies can be used in justifying particular legal rules.

---

### Sections V, VI, and VII

* Argues that the formal and substantive dichotomies are in fact aspects of a single conflict.
* Whose history is briefly traced through a hundred and fifty years of dispute
* Including moral, economic, and political.

---

### Section VIII

Outlines the contradictory sets of fundamental premises that underlie this conflict.

---

### Section IX

Conclusion

# Section I: The Jurisprudence of Rules

---

(A) "Three" Dimensions for Describing Legal directives:

::: {.r-fit-text}

1. Formal Realizability vs. Standards, principles, policies: The quality of "ruleness" in a legal directive vs. substantive objectives
2. Generality vs. particularity, e.g., rule setting age of legal majority at 21 vs. rule setting age of capacity to contract at 21.
   1. Particularity - Rules: A directive that requires response
   2. Particularity - Standards, principle or policy: substantive objective of legal order. E.g., good faith, due care, fairness
   3. Generality - wide scope intended to deal with many different fact situations
   4. General rule over or under inclusive, than particular; multiplication of particular rules undermines their realizability (too many questions); general rules should reduce judicial lawmaking; application of standard to fact produces narrow rule.
3. Formalities vs. rules designed to deter harmful behavior
   1. Sanctions: Institutions designed to prevent morally wrong or unwanted behaviors
   2. Formalities: Institutions designed to facilitate legal ordering "In every case, the formality means that unless the parties adopt the prescribed mode of manifesting their wishes, they will be ignored."
   3. How do we apply the two concepts?

:::

---

(B) Relationship between Formal Dimensions (rules as formalities)

::: {.r-fit-text}

1. Directives to deter wrongdoing
   1. Rules vs Standards: Mechanical vs. biased arbitrariness
   2. Rules: standards deter both desirable and undesirable conduct
   3. Standards can be paper tigers
   4. Rules can alert to potential danger of sanction
2. Formalities: general rules can be over and under inclusive
   1. Casting formalities as rules: "the application of the rule should only very rarely lead to the nullification of the intent of the parties."
   2. Critique of the argument for rules, two assumptions: " If the argument for rules is to work, we must anticipate that private parties will in fact respond to the threat of the sanction of nullity by learning to operate the system."; " that legal directives that looked general and formally realizable were in fact indeterminate."

:::

---

* Extreme, formally recognizable rule: directive to an official that requires him to respond to presence together or each of a list of easily distinguishable factual aspects of a situation by intervening in a determinate way.
* Standard or principle or policy: E.g., good faith, due care, fairness, unconscionably, unjust enrichment, and reasonableness.

Notebook Export
form-and-substance-in-private-law-adjudication
duncankennedy.net
Citation (Chicago Style): duncankennedy.net. form-and-substance-in-private-law-adjudication. , 2026. Kindle edition.
FORM AND SUBSTANCE IN PRIVATE LAW ADJUDICATION + Duncan Kennedy *
This article is an inquiry into the nature and interconnection of the different rhetorical modes found in American private law opinions, articles and treatises.
there are two opposed rhetorical modes for dealing with substantive issues, which I will call individualism and altruism.
are also two opposed modes for dealing with questions of the form in which legal solutions to the substantive problems should be cast.
One formal mode favors the use of clearly defined, highly administrable, general rules; the other supports the use of equitable standards producing ad hoc decisions with relatively little precedential value.
rational vindication of two common intuitions
The first

altruist views on substantive private law issues lead to willingness to resort to standards in administration,

individualism seems to harmonize with an insistence on rigid rules rigidly applied.

The second is that substantive and formal conflict in private law cannot be reduced to disagreement about how to apply some neutral calculus that will "maximize the total satisfactions of valid human wants."1

The opposed rhetorical modes lawyers use reflect a deeper level of contradiction.

we are divided, among ourselves and also within ourselves, between irreconcilable visions of humanity and society, and between radically different aspirations for our common future.

# I. THE JURISPRUDENCE OF RULES

body of legal thought that deals explicitly with the question of legal form.

It is premised on the notion the the choice between standards and rules of different degrees of generality is significant, and can be analyzed in isolation from the substantive issues that the rules or standards respond to.4

## A. Dimensions of Form as:

1. Formal Realizability.

The extreme of formal realizability is a directive to an official that requires him to respond to the presence together of each of a list of easily distinguishable factual aspects of a situation by intervening in a determinate way.

At the opposite pole from a formally realizable rule is a standard or principle or policy.

2. Generality.—The second dimension that we commonly use in describing legal directives is that of generality vs. particularity.

dimensions of generality and formal realizability are logically independent:

3. Formalities vs. Rules Designed to Deter Wrongful Behavior.

as a third dimension

Here we place at one pole legal institutions whose purpose is to prevent people from engaging in particular activities because those activities are morally wrong or otherwise flatly undesirable.

E.g., laws against murder

Formalities are premised on the lawmaker's indifference as to which of a number of alternative relationships the parties decide to enter.

By contrast, legal institutions aimed at wrongdoing attach sanctions to courses of conduct in order to discourage them.

B. Relationship of the Formal Dimensions to One Another.

The categorization of rules as formalities or as designed to

deter wrongdoing is logically independent of the issues of formal realizability and generality.

legal directives designed to deter immoral or antisocial conduct can be couched in terms of general or particular rules, general or particular standards, or some combination.

This is equally true, though less obvious in the case of formalities.

2. Formalities.

In the context of formalities the problem is that general rules will lead to many instances in which the judge is obliged to disregard the real intent of the parties choosing between alternative legal relationships.

(a) The Argument for Casting Formalities as Rules.

are as important in torts as they are in the area of pure formalities. If the rules are clear, people will invest time and energy in finding out what they are.

(b) The Critique of the Argument for Rules.

The first set of assumptions

If the argument for rules is to work, we must anticipate that private parties will in fact respond to the threat of the sanction of nullity by learning to operate the system.

But real as opposed to hypothetical legal actors may be unwilling or unable to do this.35

The second set of assumptions underlying the argument for rules concerns the practical possibility of maintaining a highly formal regime.

went into showing that legal directives that looked general and formally realizable were in fact indeterminate.38

The more general and the more formally realizable the rule, the greater the equitable pull of extreme cases of over-or underinclusion.

# II. TYPES OF RELATIONSHIP BETWEEN FORM AND SUBSTANCE

From this starting point of "value neutral" description of the likely consequences of adopting rules or standards, there are two quite different directions in which one might press the analysis of legal form.

One alternative is to attempt to enrich the initial schema by contextualizing it.

The second, and I think more important, approach ignores both the question of how rules and standards work in realistic settings and the question of how we can best solve the problem of fitting form to particular objectives.

A. Contextualization

I. Social Engineering.

"rules of law... which are applied mechanically are more adapted to property and to business transactions; standards where application proceeds upon intuition are more adapted to human conduct and to the conduct of enterprises." 42

2. The Social Science Approach.

The "scientist" as opposed to the "engineer" can ask how the choice of form will favor the interests of some participants in a conflict and disfavor others.

(b) Rules as a Means to Control Action.

(c) Rules and the Legitimacy of Judicial Action.

—In many situations that arise in our legal system, it is open to argument whether substantive norms of conduct ought to be laid down by the courts or by some other, more "democratically legitimate" institution,

In short, there may be conflict about who is the superior and who the inferior legal actor in the premises.

B. Form as Substance

The main problem with contextualization as I have presented it thus far is that it leaves out of account the common sense that the choice of form is seldom purely instrumental or tactical.

What we need is a way to relate the values intrinsic to form to the values we try to achieve through form.

The method I have adopted in place of contextualization might be called, in, a loose sense, dialetical or structuralist or historicist or the method of contradictions.73

the experience of unresolvable conflict among our own values and ways of understanding the world is here to stay.

# III. ALTRUISM AND INDIVIDUALISM

two opposed attitudes that manifest themselves in debates about the content of private law rules.

the arguments lawyers use are relatively few in number and highly stereotyped, although they are applied in an infinite diversity of factual situations.

A. The Content of the Ideal of Individualism

The essence of individualism is the making of a sharp distinction between one's interests and those of others, combined with the belief that a preference in conduct for one's own interests is legitimate, but that one should be willing to respect the rules that make it possible to coexist with others similarly selfinterested.

B. The Content of the Ideal of Altruism

The essence of altruism is the belief that one ought not to indulge a sharp preference for one's own interest over those of others.

C. Methodological Problems

There are many problems with the use of concepts like individualism and altruism.

As a result, it is impossible to "prove" or "disprove" the validity

of the two constructs.

# IV. THREE PHASES OF THE CONFLICT OF INDIVIDUALISM AND ALTRUISM

A. The Antebellum Period (1800-1870): Morality vs. Policy

Individualism was at first not an ethic in conflict with the ethic of altruism, but a set of pragmatic arguments perceived as in conflict with ethics in general.

B. Classical Individualism (1850-1940): Free Will

One major difference is the total disappearance of religious arguments, and the fading of overtly moralistic discussion.

Classical individualism," which represented not just a rhetorical shift away from the earlier emphasis on altruism, but the denial that altruism had anything at all to do with basic legal doctrines.

C. Modern Legal Thought (1900 to the present): The Sense of Contradiction

In private law, modern legal thought begins with the rejection of Classical individualism. Its premise is that Classical theory failed to show either that the genius of our institutions is individualist or that it is possible to deduce concrete legal rules from concepts like liberty, property or bodily security.

I. The Critique of Classical Individualism.

First, modern legal thought and especially modern legal education are committed to the position that no issue of substance can be resolved merely by reference to one of the Classical concepts.

Second, the problem with the concepts is that they assert the possibility of making clear and convincing on-off distinctions among fact situations, along the lines of free vs. coerced; proximate vs. remote cause; private vs. affected with a public interest.

Third, given the indeterminacy of the concepts, their inherent ambiguity as criteria of decision, it is implausible to describe the total body of legal rules as implicit in general principles like "protection of property" or "freedom of contract."

Fourth, there are numerous issues on which there exists a judicial and also a societal consensus, so that the judge's use of his views on policy will be noncontroversial.

But there are also situations in which there is great conflict. The judge is then faced with a dilemma: to impose his personal views may bring on accusations that he is acting "politically" rather than "judicially."

2. The Sense of Contradiction.

(a) Community vs. Autonomy.

(b) Regulation vs. Facilitation.—The

determinant of the distribution of desired objects and the allocation of resources to different uses.

(c) Paternalism vs. Self-Determination.—This

# V. THE CORRESPONDENCE BETWEEN FORMAL AND SUBSTANTIVE MORAL ARGUMENTS

The three sections also have a second purpose: to trace the larger dispute between individualism/rules and altruism/standards through the series of stages that lead to the modern confrontation of contradictory premises that is the subject of Section VIII.

One might attempt to link the substantive and formal dimensions at the level of social reality.

This method is hopelessly difficult, given the current limited state of the art of assessing either actual effects of decisions or their actual formal properties.

There is a strong analogy between the arguments that lawyers make when they are defending a "strict" interpretation of a rule and those they put forward when they are asking a judge to make a rule that is substantively individualist.

Likewise, there is a rhetorical analogy between the arguments lawyers make for "relaxing the rigor" of a regime of rules and those they offer in support of substantively altruist lawmaking.

The simplest of these analogies is at the level of moral argument. Individualist rhetoric in general emphasizes self-reliance as a cardinal virtue.

The same argument applies to rules that are designed to enforce substantive policies rather than merely to facilitate choice between equally acceptable alternatives.

# VI. THE CORRESPONDENCE BETWEEN FORMAL AND SUBSTANTIVE ECONOMIC ARGUMENTS

an abstract statement of the structural analogy of the formal and substantive positions,

and an historical synopsis of how the positions got to their present state.

A. An Abstract Statement of the Analogy

I. Non-intervention vs. Result-Orientation.

Suppose a situation in which the people who are the objects of the lawmaking process can do any one of three things: X, Y and Z. The lawmaker wants them to do X, and he wants them to refrain from Y and Z. If he does not intervene at all, they will do some X, some Y and some Z. As an individualist, the lawmaker believes that it would be wrong to try to force everyone to do X all the time. He may see freedom to do Y as a natural right, or believe that if he forbids Z, most people will find themselves choosing X over Y as often as if it were legally compelled. Or he may take the view that the bad side effects of state intervention to prohibit Y outweigh the benefits.

In spite of these contextual factors, there is a close analogy between the substantive individualist position and the argument for rules.

The rule advocate claims that we can best achieve the prohibition of Z through a rule that not only permits some Z (underinclusion) but also arbitrarily punishes some Y (overinclusion).

In short, the argument for rules over standards is inherently noninterventionist, and it is for that reason inherently individualist.

The main difficulty with seeing rules as noninterventionist is that they presuppose state intervention.

In other words, the issue of rules vs. standards only arises after the lawmaker has decided against the state of nature and in favor of the imposition of some

level of duty, however minimal.

2. Tolerance of Breach of Altruistic Duty: The Sanction of Abandonment.—In

Both strategies rely on the sanctioning effect of nonintervention to stimulate private activity that will remedy the evils that the state refuses to attack directly.

The self-conscious use of the sanction of abandonment as an incentive to production expresses itself on two different levels of the legal system.

In private law, it means that people are authorized to refuse to share their superfluous wealth with those who need it more than they do.

In public law, the individualist opposes welfare programs financed through the tax system as a form of compulsory collective altruism that endangers the wealth of society.

In the area of formalities, the sanction of nullity works in the

same fashion as the sanction of starvation in the substantive debate.

The parties are told that unless they use the proper language in expressing their intentions, they will fail of legal effect.

3. Transaction in General.

The argument is that both rules and the substantive reduction of
Bookmark - Page 61 · Location 1371

altruistic duty will encourage transaction in general.116

A man need not, it is true, do this or that act,—the term act implies a choice,—but he must act somehow. Furthermore, the public generally profits by individual activity. As action cannot be avoided, and tends to the public good, there is obviously no policy in throwing the hazard of what is at once desirable and inevitable upon the actor.

The state might conceivably make itself a mutual insurance company against accidents, and distribute the burden of its citizens' mishaps among all its members. There might be a pension for paralytics, and state aid for those who suffered in person or estate from tempest or wild beasts. As between individuals it might adopt the mutual insurance principle pro tanto, and divide damages when both were in fault, as in the rusticum judicium of the admiralty, or it might throw all loss upon the actor irrespective of fault. The state does none of these things, however, and the prevailing view is that its cumbrous and expensive machinery ought not to be set in motion unless some clear benefit is to be derived from disturbing the status quo. State interference is an evil, where it cannot be shown to be a good. Universal insurance, if desired, can be better and more cheaply accomplished by private enterprise.

why the activity encouraged by permitting breach of altruistic duty should lead to a public good.

he would not have generalized his position to cover all such duties, although a return to the state of nature would certainly stimulate a vast amount of activity now deterred by fear of legal intervention.

the limitation of duty should have an inhibiting effect on the activity of those subjected to uncompensated injury.

Holmes simply assumes that these inhibiting effects on desirable activity (or stimulating effects on undesirable activity) do not cancel out the gains from the "liberation of energy."

The parallel argument about rules is that "security" encourages transaction in general.

The minimization of "judicial risk" (the risk that the judge will upset a transaction and defeat the intentions of the parties) leads to a higher level of activity than would occur under a regime of standards.

The formal argument rests on the same implicit Social Darwinism as the substantive.

Security of transaction is purchased at the expense of tolerating breach of altruistic duty on the part of the beneficiary of mechanical arbitrariness.

B. Rules as an Aspect of Classical Laissez-Faire

The conclusion of the abstract consideration of the relationship of form and substance is that there is a sound analytical basis for the intuition of a connection between individualism and rules.

It is not a connection that is necessary in practice, or even verifiable empirically. It consists in the exact correspondence between the structures of the two arguments.

I. Laissez-Faire.—It is not easy to reconstruct the Classical individualist economic vision, especially if we want to understand it from the inside as plausible, rather than absurd or obviously evil.

While there were several strands of argumentation, the most important seems to have been the idea that the outcome of economic activity within a common law framework of contract and tort rules mechanically applied would be a natural allocation of resources and distribution of income.

2. The Altruist Attack on Laissez-Faire.—The altruist attack on laissez-faire denied the neutrality of the outcomes of bargaining within the background rules.

# VII. THE POLITICAL ARGUMENTS ABOUT JUDICIAL RESULT ORIENTATION

The advocate of rules argues that the cast-

ing of law as standards is inconsistent with the fundamental rights of a citizen of a democratic state.

There are two branches to the argument.

institutional competence

political question gambits.

The premise of the institutional competence argument is that judges do not have the equipment they would need if they were to try to determine the likely consequences of their decisions for the total pattern of social activity.

The premise of the political question gambit is that there is a radical distinction between the activity of following rules and that of applying standards.

It seems intuitively obvious that both of these gambits are prototypically individualist.

It would therefore seem reasonable to expect that we would find an exactly

parallel substantive claim that the judge should not attempt to impose a high standard of altruistic duty because he has neither the knowledge nor the democratic legitimacy required for the enterprise.

the central thesis of the modern conservative attack on judicial activism in both public and private law.127

A. The Origins of the Institutional Competence and Political Question Gambits

I. The Classical Individualist Position on Judicial Review.

2. The Altruists Accept the Individualist Theory of the Judicial Role.

First, the altruists pointed out that the individualist public law position was conceptualist.

3. The Inconsistency of the Altruist Distinction Between Public and Private Law.

First, Classical individualist private law was no less dependent on conceptualism than public law for its claim to neutrality and legitimacy.

Second, a major strand in the public law argument was precisely that common law rules of property, tort and contract represented a massive state intervention in the economy.

Thus there is really a single altruist critique of constitutional and common law judicial lawmaking.

If the gambits are valid in public but not in private law, it must be because we should draw different conclusions from the discovery of the political element according to whether we are dealing with the Constitution or with common law institutions.

B. The Individualist Character of the Gambits in Private Law

Judicial private lawmaking takes place precisely in those marginal and interstitial areas of the legal system where there is no unequivocal or even extremely suggestive indication of legislative will.

In this individualist argument, the judge has a legitimate function as a marginal and interstitial lawmaker, and as a law applier, so long as he eschews result orientation.

The altruist response is that the three tiered system leads to deference to private power, rather than to the legislature.

The will that the judge is enforcing when he refuses to interfere with freedom of contract is the will of the parties, or of the dominant party, if the relationship is an unequal one.

Once one accepts such a conception, the three-tiered structure collapses. The judge, by hypothesis, cannot appeal to a legislative command, and the common law with which she is to harmonize her result points in both directions at the same time.

C. Two Proposed Solutions to the Political Dilemma

While in 1940 one might reasonably have asserted that the net effect of individualist-altruist conflict in private law had been to deprive the judge of any basis for deciding cases beyond personal orientation to results, there have since been two major attempts to help him out of this embarrassing situation, and to restore the prestige of law by vindicating its claim to autonomy from politics.

The law and economics movement,148 insomuch as it purports to offer a theory of what judges should do, is an attempt to formalize the three-tiered system while at the same time substituting the authority of economic science for that of the historical common law.

The problem with this position, even supposing that one accepts its revolutionary rejection of the common law tradition, is that efficient resource allocation cannot provide a determinate answer for the judge's dilemma as to what law to make.

The alternative proposal, that the judge engage in "reasoned elaboration" of the immanent social purposes of the legal order, or that he decide on the basis of a "moral discourse," rejects the dichotomy of factual judgments and value judgments.151

But it also creates a three-tiered structure.

There is the outcome of private activity. There is judicial intervention via reasoned elaboration. And there is legislative intervention in pursuit of goals that the judge must ignore.

The postulate of democracy then requires the judge to restrict his lawmaking to the narrowest possible compass by adopting a regime of formally realizable general rules.

But a compromise of this kind is as hostile to the altruist program of result orientation as it is to individualism.

My own view is that the ideologists offer a convincing description of reality when they answer that there is no core. Every occasion for lawmaking will raise the fundamental conflict of individualism and altruism, on both a substantive and a formal level. It would be convenient, indeed providential, if there really were a core, but if one ever existed it has long since been devoured by the encroaching periphery.

# VIII. FUNDAMENTAL PREMISES OF INDIVIDUALISM AND ALTRUISM

In this section, I will argue that the persistence of these attitudes as organizing principles of legal discourse is derived from the fact that they reflect not only practical and moral dispute, but also conflict about the nature of humanity, economy and society.

There are two sets of conflicting fundamental premises that are available when we attempt to reason abstractly about the world, and these are linked with the positions that are available to us on the more mundane level of substantive and formal issues in the legal system.

Individualism is associated with the body of thought about man and society sometimes very generally described as liberalism.

The whole enterprise of Classical individualist conceptualism was to show that a determinate legal regime could be deduced from liberal premises, as well as derived from individualist morality and practicality.

The same is true on the altruist side.

The organicist premises with which the altruist responds to the liberal political argument are on another level altogether from the moral and practical assertions we have dealt with up to now.

The importance of adding this theoretical dimension to the moral and practical is that it leads to a new kind of understanding of the conflict of individualism and altruism.

In particular, it helps to explain what I called earlier the sticking points of the two sides—the moments at which the individualist, in his movement towards the state of nature, suddenly reverses himself and becomes an altruist, and the symmetrical moment at which the altruist becomes an advocate of rules and self-reliance rather than slide all the way to total collectivism or anarchism.

A. Fundamental Premises of Individualism

The characteristic structure of individualist social order consists of two elements.154

First, there are areas within which

actors (groups or individuals) have total arbitrary discretion (often referred to as total freedom) to pursue their ends (purposes, values, desires, goals, interests) without regard to the impact of their actions on others.

Second, there are rules, of two kinds: those defining the spheres of freedom or arbitrary discretion, and those governing the cooperative activities of actors—that is, their activity outside their spheres of arbitrariness.

(a) A is permitted to ignore B and carry on within the sphere of his discretion as though B did not exist.

(b) A and B are negotiating, either as private contracting parties or as public legislators, the establishment of some rules to govern their future relations.

(c) A and B are once again permitted to ignore one another, so long as each follows the rules that govern their cooperative behavior.

The creation of an order within which there are no occasions on which it is necessary for group members to achieve a consensus about the ends they are to pursue, or indeed for group members to make the slightest effort toward the achievement of other ends than their own, makes perfect sense if one operates on the premise that values, as opposed to facts, are inherently arbitrary and subjective.

The subjectivity of values means that it is, by postulate, impossible to verify directly another person's statement about his experience of ends.

The postulate of the arbitrariness of values means that there is little basis for discussing them.

B. Fundamental Premises of Altruism

The utopian counter-program of altruist justice is collectivism.157 It asserts that justice consists of order according to shared ends.

Altruism denies the arbitrariness of values.

It asserts that we understand our own goals and purposes and those of others to be at all times in a state of evolution, progress or retrogression,

terms of a universal ideal of human brotherhood.

Altruism also denies the subjectivity of values.

My neighbor's experience is anything but a closed book to me.

Altruism offers its own definitions of legal certainty, efficiency, and freedom.

The certainty of individualism is perfectly embodied in the calculations of Holmes’ "bad man," who is concerned with law only as a means or an obstacle to the accomplishment of his antisocial ends.

To the altruist this is a kind of collective insanity by which we traduce our values while pretending to define them.

"Efficiency" in the resolution of disputes is a pernicious objective unless it includes in the calculus of benefits set against the costs of administering justice the moral development of society through deliberation on the problem of our apparently disparate ends.

The "freedom" of individualism is negative, alienated and arbitrary.

When the group creates an order consisting of spheres of autonomy separated by (property) and linked by (contract) rules, each member declares her indifference to her neighbor's salvation—washes her hands of him the better to "deal" with him.

C. The Implications of Contradictions Within Consciousness

The explanation of the sticking points of the modern individualist and altruist is that both believe quite firmly in both of these sets of premises, in spite of the fact that they are radically contradictory.

The altruist critique of liberalism rings true for the individualist who no longer believes in the possibility of generating concepts that will in turn generate rules defining a just social order.

The liberal critique of anarchy or collectivism rings true for the altruist, who acknowledges that after all we have not

overcome the fundamental dichotomy of subject and object.

So long as others are, to some degree, independent and unknowable beings, the slogan of shared values carries a real threat of a tyranny more oppressive than alienation in an at least somewhat altruistic liberal state.

The meaning of contradiction at the level of abstraction is that there is no metasystem that would, if only we could find it, key us into one mode or the other as circumstances "required."

Second, the acknowledgment of contradiction means that we cannot "balance" individualist and altruist values or rules against equitable standards, except in the tautological sense that we can, as a matter of fact, decide if we have to.

Third, the recognition that both participants in the rhetorical struggle of individualism and altruism operate from premises that they accept only in this problematic fashion weakens the individualist argument that result orientation is dynamically unstable.

Finally, the acknowledgement of contradiction makes it easier to understand judicial behavior that offends the ideal of the judge as a supremely rational being.

In place of the apparatus of rule making and rule application, with its attendant premises and attitudes, we come suddenly on a gap, a balancing test, a good faith standard, a fake or incoherent rule, or the enthusiastic adoption of a train of reasoning all know will be ignored in the next case.

In terms of individualism, the judge has suddenly begun to act in bad faith. In terms of altruism she has found herself.

The only thing that counts is this change in attitude, but it is hard to imagine anything more elusive of analysis.
