---
title: "Syllabus"
format:
  html:
    toc: false
    number-sections: false
    colorlinks: true
  pdf:
    documentclass: article
---

## Welcome to Introduction to Philosophy

In this course, we will use David Chalmer's book ***Reality+*** to look at questions humans have been asking for thousands of years. While the primary focus of the book is look at one question in particular "Are we in a simulation?", we use this question to frame others such as: "What does it mean to know that the sky is blue?", "is murder really wrong?", "How did I come to know that murder is wrong?".

## 💻 Class Meeting Times

- 📆 Mondays and Wednesdays
- ⌚ 10:30am - 11:45am

## Course Convenor

Dr. Monty Reynolds
📧 mreynolds1@stetson.edu

Office Hours:

- When:
  * Tuesday: 1:00–3:00 PM
  * Thursday: 1:00–3:00 PM
- Where: Elizabeth Hall 104
- How to book: Drop in, email, or book via [Microsoft Bookings](https://outlook.office.com/bookwithme/user/59570715559b43fdabc651a89a3ed839@stetson.edu?anonymous&ismsaljsauthenabled&ep=plink)

## Course Information

Introduction to Philosophy: Value, Meaning, and Humanity's Place in the Modern World

Times: 10:30-11:45
Days: Mons and Weds or Tues Thurs
Where: Davis Hall 209

## Required Texts:

Chalmers, David J.. Reality+: Virtual Worlds and the Problems of Philosophy. United Kingdom: Penguin Books Limited, 2022.

Here is an amazon link to the book: https://www.amazon.com/Reality-Virtual-Worlds-Problems-Philosophy/dp/0393635805

This will also be supplemented with handouts.

## Expectations:

Come prepared to engage with assigned readings in class, referencing specific passages as prompted by the instructor.

Bring physical or digital copies of readings to class for annotation and short reflections.

Submit all assignments via Canvas by the due date.

Active participation and regular attendance are essential for success.

Success: Active participation, timely submissions, and attendance are key.

## Grading Calculation

***Weekly Reflections:*** Each reflection is worth a possible total of 8 points. There are 12 possible reflections. I will only grade 8 or your best reflections.

{{< include ./weeklies/index.qmd >}}

***Reflective Analysis 1 & 2 (160 points):*** Each reflective analysis is worth a possible total of 20 points per category, times 4 categories equals 80 points times 2 reflection pieces.

{{< include ./critical-reflections/index.qmd >}}

***Essay 1 & 2 (80 points):*** Each Quiz is worth a possible total of 10 points per category, times 4 categories equals 40 points times 2 Quizzes.

{{< include ./quizzes/index.qmd >}}

***Presentation:*** Your grade in this area depends on your preparation and participation in the DND class meetings. [We will use the dnd adventure sheet linked here to gage participation](https://drive.google.com/drive/folders/1ZAXxdpvv5jzylj8_18jXUTI68o9MLrXw?usp=sharing).

{{< include ./d&d-campaigns/index.qmd >}}

Students will be evaluated based on a total of 640 points, with the final grade determined by the percentage of points earned. The components are as follows:

### Grading Rubric

{{< include ./rubrics/rubric-1.qmd >}}

##### Attendance (5% of final grade, 32 points):

* Based on unexcused absences throughout the semester.

Grading Scale (equal increments of 8 points):

||||
|---|---|---|
| 0–1 | unexcused absences: | 32 points |
| 2 | unexcused absences: | 24 points |
| 3–4 | unexcused absences: | 16 points |
| 5–6 | unexcused absences: | 8 points |
| 6 | unexcused absences: | 0 points |

### Reading Schedule

***Adjust all dates by one for Tuesday Thursday Course***

***Weeklies Due Every Monday Starting Jan 19***

Wed Jan 14, handouts

Mon Jan 19 MLK Day, no classes

Wed Jan 21, Chapter 2, Simulation Hypothesis

Mon Jan 26, Chapter 3, Knowledge

Wed Jan 28, The external world, ch. 4

Mon Feb 2, ch. 5, Possible realities, bostrom and Moravec

Wed Feb 4, ch. 6, What is Reality?

Mon Fed 9, ch. 7, Is God a hacker in the universe up?

Wed Fed 11, ch. 8 Information, 2nd DND Adventure, Student Led

Mon Feb 16, ch. 9, On Bits

Wed Feb 18, ch. 10, Reality and Virtual Reality

Mon Feb 23, ch. 11, Illusion Machines

Wed Feb 25, Quiz 1

Mon Mar 02, Spring Break

Wed Mar 4, Spring Break

Mon Mar 9, ch. 13 ch. 12, 3rd DND Adventure, Student Led

Wed Mar 11, ch. 14, Mind and body Realism inside a virtual universe

Mon Mar 16, ch. 15, 4th DND Adventure, Student Led

Wed Mar 18, ch. 16, The extended mind hypothsis

Mon Mar 23, ch. 17 Critical Reflection Due

Wed Mar 25, ch. 18, Virtual ethics and intentiality

Mon Mar 30, ch. 19, Social Ontology inside virtual worlds

Wed Apr 1, ch. 20, 5th DND Adventure on Sense and Reference, Student Led

Mon Apr 6, ch. 21, Cause and effect inside virtual systems

Wed Apr 8, ch. 22, Mathematical, physical and cultural structualism

Mon Apr 13, ch. 23, Virtual Eden?

Wed Apr 15, ch. 24, Brains in a Vat

Mon Apr 20, TBD

Wed Apr 22, TBD

Mon Apr 27, TBD

Wed Apr 29, last day of classes, Final Quiz

Paper Due on Day of Final Quiz (Submit on Canvas)

### University Supports and Policies

Please Note: Oral appeals for grade changes are NOT accepted. If you feel that you have an extremely strong case for a grade change, you may submit a one-page essay explaining your reasons to me within one week of your work being returned.

A.Honor Code: University rules concerning scholastic dishonesty will be strictly followed. Any attempt at academic cheating will be referred to the Honor Council. I expect you to abide by the Honor Code that we have adopted here at Stetson. Please sign all work “Pledged, your name.” University rules concerning scholastic dishonesty will be strictly followed. As a community of intellectual inquirers, we are all committed to academic integrity and honesty.  The Stetson University Student Government Association, on its own initiative, recently drafted a proposal for an honor code, a powerful statement of the student body’s commitment to this community of honor and integrity. For this reason, all work that you turn in must be your own. Any contribution from others must be clearly acknowledged. Unauthorized assistance on exams (take-home as well as in-class), research papers, or projects can be neither given nor received. The University has fully endorsed its honor system and abides by its precepts. If you have questions regarding the method/procedure for citing the work of others, please feel free to consult us.

The Department of Philosophy expects academic honesty of all students; we expect all students to abide by Stetson’s honor code and to adhere to the honor system. Academic dishonesty includes, but is not limited to, altering or misusing documents, plagiarizing, misrepresentation, knowingly providing false information, colluding, and other forms of cheating. Students should read and follow Stetson’s definitions and policies on ‘Academic Honesty,’ the honor code, and the honor system in Connections: The Campus Life Handbook and Calendar. It is the student’s responsibility to be familiar with these definitions and policies; ignorance of them is not an acceptable excuse for violating them. Cases of suspected academic dishonesty, including plagiarism, will be referred to the Academic Honor Council, as per departmental policy.

The honor code can be found online at the following address:http://www.stetson.edu/honorsystem/  http://www.stetson.edu/honorsystem/

B.Assignment standards: Late Work: All assignments must be handed in on time: late work will be docked a half-letter grade per day unless you get my approval for an extension before the due date. (Student athletes and others on school business: please, be advised to turn your assignments in BEFORE you leave, not after you return). No make-up exams or quizzes will be given without documented University accepted excuse (and they will differ from the ones given in class). This includes group quizzes.

C.Accommodation: Writing Center: Many students experience difficulty writing research papers. For that reason, Stetson University supports a Writing Center, located on the Second Floor of the Library. I have found that one or two visits to the Writing Center can make a tremendous difference in the quality of a paper. If you find that you have trouble with your written assignments, I strongly encourage you to seek the help of the Writing Center. The Academic Success Center provides academic and disability resources for all Stetson University Students. Students who anticipate barriers related to the format or requirements of a course should meet with me to discuss ways to ensure full participation. If disability-related accommodations are necessary, please register with the Academic Success Center (386-822-7127; www.stetson.edu/asc). You and I, and the ASC, will plan how best to coordinate accommodations.
Sheridan’s writing center hours: W 2-6, F 12-3.

The ASC also coordinates free tutoring on campus for students. You can meet with a tutor to review principles, learn content-specific study strategies, and enhance content area knowledge. To review the tutoring options available and schedules, please see our website www.stetson.edu/asc/tutoring/php.

2.Counseling: Counseling: College can be extremely stressful for students, especially if this is the first time you’ve been away from home for an extended period of time or if there are other pressures that you are facing. For this reason, you may find it helpful to consult the University Counseling Center. Here is their contact information:

Phone number: 386-822-8900

Location:  The office is located in Griffith Hall

Office hours: Weekdays from 8:00 a.m. to 4:30 p.m.

If a student experiences a mental health emergency after hours, they can simply call Public Safety (386-822-7300) and ask to speak with the on-call counselor.

We are staffed with qualified professional counselors who are trained to support and guide students through difficult transitions, experiences, and feelings.

Counseling is confidential and free of charge for all currently enrolled Stetson University students.

If experiencing a mental health crisis, you may also call 386-822-8740 to be connected to Volusia County Crisis Response Team: If having thoughts of harming yourself or others, select option one. For all other mental health needs select option nine.

For medical emergencies call 911.

Schedule of Readings/Assignments: subject to change as needed, it is YOUR responsibility to regularly check blackboard for announcements.

Students are required to check their Stetson email and Canvas accounts frequently, daily if possible. Do not use technology as an excuse for not completing an assignment/quiz or for submitting an assignment/quiz late or improperly. Late assignments/submissions are not accepted.

All students will be asked to verify in an online quiz that they agree and will abide by the procedures and policies presented in this syllabus. If you do not feel you can abide by the course rules, please drop the course.

Any recordings of this class (audio, video, or otherwise) may ONLY be used for personal academic use. Recordings may NOT be shared with other people without written consent from the professor. The information contained in recordings constitutes intellectual property and is protected under federal copyright laws. This information may NOT be published or quoted without the express written consent of the professor and without giving proper identification and credit to the professor. Recordings of this class may not be used in any way against the faculty member, teaching assistant, other lecturer, or students whose classroom comments are recorded as part of the class. Violation of these stipulations will result in being reported to the Office of Community Standards.

D. Food Insecurity: At Stetson University, we are committed to supporting students’ well-being, including ensuring access to nutritious food. If you are experiencing a lack of access to safe and nutritious food, the Hatters Helping Hatters Food Pantry is her to help. The Food Pantry is a free, no-questions-asked supplemental food resource for all Stetson students, staff & faculty. Food Pantry location:

* Carlton Union Building (CUB 278), open 24 hours.
