---
author: Introduction to Philosophy by Philip A. Pecorino is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License. [here](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm)
---

# Ch 7, Feb 7: Is God a Hacker in the next Universe Up?

## Is God a Hacker?

---

### What is God?

* Creator
* All Powerful
* All Knowing
* All Good

---

### What about the Hacker?

- [ ] Creator?
- [ ] Powerful?
- [ ] Knows Stuff?
- [ ] Good?

---

Important Distinction:

- Local vs. Cosmic
- Local Knowledge vs. Global Knowledge
- Local Power vs. Global Power

## Proofs for the Existence of God

---

### Ontological Argument

::: {.notes}

This is the  a priori  argument : prior to considering the existence of the physical universe.  This is reasoning without bringing in any consideration of the existence of the universe or any part of it.  This is an argument considering the idea of god alone.

The argument is considered to be one of the most intriguing ever devised.  It took over 400 years for Philosophers to realize what its actual flaws were.  As an “a priori” argument, the Ontological Argument tries to “prove” the existence of God by establishing the necessity of God’s existence through an explanation of the concept of existence or necessary being .

:::

---

VIEW: [Ontological Argument](https://youtu.be/FmTsS5xFA6k?si=VYTUlDTrxcRIiji9)

VIEW: [Ontological Argument and Anselm: Crash Course Philosophy #9](https://youtu.be/FmTsS5xFA6k?si=VYTUlDTrxcRIiji9)

---

::: {.notes}

Anselm, Archbishop of Canterbury first set forth the Ontological Argument in the eleventh century.  This argument is the primary locus for such philosophical problems as whether existence is a property and whether or not the notion of necessary existence is intelligible.  It is also the only one of the traditional arguments that clearly leads to the necessary properties of God, such as Omnipotence, Omniscience, etc. Anselm’s argument may be conceived as a “reductiio ad absurdum” argument.  In such an argument, one begins with a supposition, which is the contrary to what one is attempting to prove.  Coupling the supposition with various existing certain or self-evident assumption will yield a contradiction in the end.  This contradiction is what is used to demonstrate that the contrary of the original supposition is true.

:::

---

::: {.r-fit-text}

Two Forms:

Form 1:

Premises:

(1.a.) Anselm- the supreme being- that being greater than which none can be conceived (gcb)

(1.b.) the gcb must be conceived of as existing in reality and not just in the mind or else the gcb is not that being greater than which none can be conceived.

Suppose (S) that the greatest conceivable being (GCB) exists in the mind alone and not in reality(gcb1). \

Then the greatest conceivable being would not be the greatest conceivable being because one could think of a being like (gcb1) but think of the gcb as existing in reality (gcb2) and not just in the mind. \

So, gcb1 would not be the GCB but gcb2 would be.

Conclusion:

Thus to think of the GCB is to think of the gcb2, i.e. a being that exists in reality and not just in the mind.

:::

---

::: {.r-fit-text}

Form 2: God as Necessary Being

Premises:

(a) God is either a necessary being or a contingent being. \
(b) There is nothing contradictory about god being a necessary being \
(c) So, it is possible that god exists as a necessary being. \
(d) So if it is possible that God is a necessary being then God exists. \
(e) Because God is not a contingent being. \

Conclusion:

God must exist as a necessary being.

:::

::: {.notes}

Notes on the Ontological arguments of Anselm and Descartes

Anselm begins by defining the most central term in his argument - God. Without asserting that God exists, Anselm asks what is it that we mean when we refer to the idea of "God." When we speak of a God, Anselm implies, we are speaking of the most supreme being. That is, let "god" = "something than which nothing greater can be thought." Anselm's definition of God might sound confusing upon first hearing it, but he is simply restating our intuitive understanding of what is meant by the concept "God." Thus, for the purpose of this argument let "God" = "a being than which nothing greater can be conceived."

Within your understanding, then, you possess the concept of God. As a non-believer, you might argue that you have a concept of unicorn (after all, it is the shared concept that allows us to discuss such a thing) but the concept is simply an idea of a thing. After all, we understand what a unicorn is but we do not believe that they exist. Anselm would agree.

:::

---

Two key points have been made thus far:

(1) When we speak of God (whether we are asserting God is or God is not), we are contemplating an entity whom can be defined as "a being which nothing greater can be conceived.";

(2) When we speak of God (either as believer or non-believer), we have an intra-mental understanding of that concept, i.e. the idea is within our understanding.

::: {.notes}

Anselm continues by examining the difference between that which exists in the mind and that which exists both in the mind and outside of the mind as well. What is being asked here is: Is it greater to exist in the mind alone or in the mind and in reality (or outside of the mind)? Anselm asks you to consider the painter, e.g. define which is greater: the reality of a painting as it exists in the mind of an artist, or that same painting existing in the mind of that same artist and as a physical piece of art. Anselm contends that the painting, existing both within the mind of the artist and as a real piece of art, is greater than the mere intra-mental conception of the work. Let me offer a real-world example: If someone were to offer you a dollar, but you had to choose between the dollar that exists within their mind or the dollar that exists both in their mind and in reality, which dollar would you choose? Are you sure...

:::

---

At this point, we have a third key point established:

(3) It is greater to exist in the mind and in reality, then to exist in the mind alone.

Have you figured out where Anselm is going with this argument?

(A) If God is that than greater which cannot be conceived (established in #1 above);
(B) And since it is greater to exist in the mind and in reality than in the mind alone (established in #3 above);
(C) Then God must exist both in the mind (established in #2 above) and in reality;
(D) In short, God must be. God is not merely an intra-mental concept but an extra-mental reality as well.

::: {.notes}

But why? Because if God is truly that than greater which cannot be conceived, it follows that God must exist both in the mind and in reality. If God did not exist in reality as well as our understanding, then we could conceive of a greater being i.e. a being that does exist extramentally and intramentally. But, by definition, there can be no greater being. Thus, there must be a corresponding extra-mental reality to our intra-mental conception of God. God's existence outside of our understanding is logically necessary.

Sometimes, Anselm's argument is presented as a Reductio Ad Absurdum (RAA). In an RAA, you reduce to absurdity the antithesis of your view. Since the antithesis is absurd, your view must be correct. Anselm's argument would look something like this:

:::

---

1. Either [God exists] or [God does not exist].

2. Assume [God does not exist] (the antithesis of Anselm's position)

3. If [God does not exist] (but exists only as an intra-mental concept), then that being which nothing greater which can be conceived, is a being which a greater being can be conceived. This is a logical impossibility (remember criterion #3);

4. Therefore, [God does not exist] is incorrect;

Conclusion:

5. Therefore [God exists].

---

### Clarifications:

* The argument is not that "If you believe that god exists then god exists".
* That would be too ridiculous to ask anyone to accept that if you believe that X exists and is real then X exists and is real.
* The ontological argument does not ask a person to assume that there is a deity or even a GCB.

::: {.notes}

It asks anyone at all to simply THINK of the deity as the GREATEST CONCEIVABLE BEING and then it indicates that a being that exists in reality (outside of the mind) is greater than one that is just in the mind (imagination). So, the conclusion is that if you think of the GCB you must THINK that the GCB exists not just in your thinking (mind) but in reality (outside of your mind) as well.

It is greater to think of a being existing outside of the mind as well as in the mind so if you think of the GCB you must THINK THAT the GCB exists not just inside of the mind (imagination) but outside of the mind as well (in reality).

Look at it this way: Anselm invites people to think about a certain conception of the deity,i.e., that of the GCB.  What Anselm did was to place into the concept itself the idea that the being must exist outside of the mind and in the realm of the real and not just inside the mind in the realm of imagination.  So you THINK of the GCB and what are you doing when you do that?  You must think that the GCB exists outside of the mind and in the realm of the real and not just inside the mind in the realm of imagination.  Why must you think that?  Because it you did not think that, then you would not be thinking of the GCB as defined by Anselm.

It is like this:  Think of a triangle.  If you do you must think of a three sided figure lying on a plane with three angles adding up to 180 degrees.  Why? Because if you are not thinking of a three sided figure lying on a plane with three angles adding up to 180 degrees then you are not thinking of a triangle.  So IF you are to THINK of a triangle you must THINK of a three sided figure lying on a plane with three angles adding up to 180 degrees.

If you are to THINK of a GCB you must THINK that the being must exist outside of the mind and in the realm of the real and not just inside the mind in the realm of imagination. Why? Because if you are not thinking that the being must exist outside of the mind and in the realm of the real and not just inside the mind in the realm of imagination then you are not thinking of the GCB.

In all of this it is only thinking.  Anselm proved what must be thought about the GCB given how the GCB was defined and not whether the GCB actually exists.

:::

---

A variation of this argument by Alvin Plantinga exists.  It is known as the Modal Version of the Ontological Argument:

::: {.r-fit-text}

1. To say that there is possibly a God is to say that there is a possible world in which God exists.

2. To say that God necessarily exists is to say that God exists in every possible world.

3. God is necessarily perfect (i.e. maximally excellent)

4. Since God is necessarily perfect, he is perfect in every possible world.

5. If God is perfect in every possible world, he must exist in every possible world, therefore God exists.

6. God is also maximally great.  To be maximally great is to be perfect in every possible world.

7. Therefore:  “it is possible that there is a God,” means that there is a possible which contains God, that God is maximally great, and the God exists in every possible world and is consequently necessary.

8. God’s existence is at least possible.

9. Therefore:  as per item seven, God exists.

:::

---

Rene Descartes, 1596 - 1650, is also credited with formulating a version of the ontological argument. One possible presentation of the Cartesian argument is as follows:

1. If there is a God it is a perfect being;

2. A perfect being possesses all possible perfections;

3. Existence is a perfection;

4. Therefore, God necessarily possesses the quality of existence. Simply, God exists.

---

The actual texts:

[Anselm’s Philosophy](https://sourcebooks.fordham.edu/basis/anselm-intro.asp)

Anselm’s Argument

[Monologium](https://sourcebooks.fordham.edu/basis/anselm-monologium.asp)

[Proslogium](https://sourcebooks.fordham.edu/basis/anselm-proslogium.asp)

[Guanilo’s Response and Anselm’s response to Guanilo](https://sourcebooks.fordham.edu/basis/anselm-gaunilo.asp)

---

PROBLEMS:

The problem with the ontological argument is NOT

1) that some people refuse to think of the GCB or

2) that some people have a resistance to a belief in a deity

3) that some people just refuse to accept the deity

NO NO NO the problem with the Argument is that it has FLAWS. It has a LOGICAL MISTAKE in it.

What is that error in the argument???

## PROBLEM:

Conclusion of the argument is : Thus, to think of the GCB is to think of the gcb2, i.e. a being that exists in reality and not just in the mind \

* Immanuel Kant noticed that to think of the GCB is to think of the gcb2, i.e. a being that exists in reality and not just in the mind \

* BUT to think of the gcb2 as a being that exists in reality and not just in the mind, does not prove that the gcb2 does actually exist in reality ONLY that a person MUST THINK that the gcb2 does actually exist in reality

* But for Kant and many after him , the notion of "Existence" is not a predicate:  You cannot include it within the idea of the thing itself. You cannot think anything into existence by including existence as a property of that thing.

# Counter Arguments to Anselm:

## I. The Most Perfect Island

Gaunilon, a contemporary of Anselm, had two major criticisms of the ontological argument.

* First: If by "God" we do mean "that than greater which can not be conceived," then the concept is meaningless for us. We can not understand, in any meaningful way, what exactly is meant by such words. The reality behind the term is completely transcedent to the human knower;

* Second: Even if we grant that the concept of God as "that than greater which can not be conceived" exists in the understanding, there is no reason to believe that the concept necessitates the extra-mental reality of God. After all, I can imagine the most perfect island, glorious in every detail, but there is nothing about my understanding of the island that forces us to admit the island exists.

---

## II. Existence is not a predicate

Immanuel Kant (1724 - 1804), offered what many believe to be a damning critique of Anselm's ontological argument.

* Let us return to our discussion of unicorns and God.
* Anselm has argued that there exists a difference between the concept of "unicorn" as it exists intra-mentally and extra-mentally.
* If we claim that the "unicorn" is, we are somehow adding to the concept. We are endowing the concept with an additional predicate, i.e. the quality that it is.

The point of Anselm's argument is that the predicate of existence can be demonstrated for the concept of "God."

::: {.notes}

Kant does not agree with Anselm's treatment of existence as a predicate. The concept of "unicorn" is not changed in any way if we claim that it is. Nor is the concept damaged if we claim that unicorns are not. According to Kant,"...we do not make the least addition to the thing when we further declare that this thing is." If existence is not a predicate, then Anselm's argument has not demonstrated any meaningful information.

Kant thought  that, while the concept of a supreme being was useful, it was only an idea, which in and of itself could not help us in our determining the correctness of the concept.  While it was a possibility, he felt that the “a priori” stance of the argument it would be necessary to buttress it with experience.

For Kant what Anselm did was to prove that humans MUST THINK THAT a deity exists in reality and not just in the mind as an idea as the GCB but that does not mean that the GCB actually does exist in reality.  The idea of the GCB exists and the idea of the GCB as an actual being does exist but the reality or actuality of the GCB is not established based on the thoughts alone.

:::

## Think of three situations:

1. You go home and look at the top of your dresser. You could use some money and as you look there you imagine seeing ten ten dollar bills.

2. You go home and look at the top of your dresser. You could use some money and as you look there you see ten MONOPOLY ten dollar bills.

3. You go home and look at the top of your dresser. You could use some money and as you look there you seeing ten real ten dollar bills.

::: {.notes}

Which of the three is the greatest or best situation?    #3 is.

But just thinking about #3 does not actually add any money to your total amount.

This is Kant's point.

Thinking about the GCB logically entails THINKING that the GCB must exist in reality and not just in the imagination. But thinking about the GCB as existing in reality and not just in the imagination does not prove that the GCB actually does exist in reality and not just in the imagination. It is just an idea about what exists.

:::

## III. The Greatest Conceivable EVIL Being.

::: {.notes}

As an “a priori” argument, the Ontological Argument tries to “prove” the existence of God by establishing the necessity of God’s existence through an explanation of the concept of existence or necessary being.  As this criticism of the Ontological Argument shows, the same arguments used to prove an all-powerful god, could be used to prove an all-powerful devil.  Since there could not exist two all-powerful beings (one’s power must be subordinate to the other), this is an example of one of the weaknesses in this type of theorizing. Furthermore, the concept of necessary existence, by using Anselm’s second argument, allows us to “define” other things into existence.

The argument could prove the existence of that being more EVIL than which no other can be conceived just as easily as it supposedly proves the existence of the being that is the greatest conceivable being.

Think of a being that is the most evil being that can be conceived.  That being must be conceived of as existing in reality and not just in the mind or it wouldn’t be the most evil being which can be conceived for a being that does not exist in reality is not evil at all.

:::

## IV. Empiricist Critique

Aquinas, 1225 - 1274, once declared the official philosopher of the Catholic Church, built his objection to the ontological argument on epistemological grounds.

* Epistemology is the study of knowledge. It is a branch of philosophy that seeks to answer such questions as: What is knowledge?; What is truth?; How does knowing occur?; et cetera. Aquinas is known as an empiricist. Empiricists claim that knowledge comes from sense experience. Aquinas wrote: "Nothing is in the intellect which was not first in the senses."

* Within Thomas' empiricism, we can not reason or infer the existence of God from a studying of the definition of God. We can know God only indirectly, through our experiencing of God as Cause to that which we experience in the natural world. We can not assail the heavens with our reason; we can only know God as the Necessary Cause of all that we observe.

* Alvin Plantiga offers a counter argument to the counter arguments that at least establishes the rational acceptability of theism as it appears to support the idea that it is possible that the greatest conceivable being does exist.

---

### Other Philosophers and their Critiques:

(a) [René Descartes, from The Philosophy of Descartes in Extracts from His Writings. H. A. P. Torrey. New York, 1892. P. 161 et seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#DESCARTES)

(b) [Benedict Spinoza, from The Chief Works of Benedict de Spinoza. Translated by R.H.M.Elwes. London, 1848. VoI. II., P. 51 at seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#SPINOZA)

(c) [John Locke, from An Essay Concerning Human Understanding. London: Ward, Lock, Co. P. 529 et seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#LOCKE)

(d) [Gottfried W. Leibniz, from New Essays Concerning Human Understanding. Translated by A.G. Langley. New York, 1896. P. 502 at seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#LEIBNIZ)

(e) [Immanuel Kant, from Critique of Pure Reason. Translated by F. Max Muller. New York, 1896. P-483 et seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#KANT)

(f) [Georg W.F. Hegel, from Lectures on the History of Philosophy. Translated by E. S. Haldane and F.H. Simson. London, 1896. Vol. III., p. 62 et seg.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#HEGEL)

(g) [J. A. Dorner from A System of Christian Doctrine. Translated by A. Cave and J. S. Banks, Edinburgh, 1880. Vol. I., p. 216 et seq](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#J.%20A.%20DORNER)

(h) [Lotze, Microcosmus. Translated by E. Hamilton and E. E. C. Jones. Edinburgh, 1887. Vol. II., p. 669 et seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#LOTZE)

(i) [Robert Flint, from Theism. New York, 1893. Seventh edition. P. 278 et seq.](https://www.qcc.cuny.edu/socialSciences/ppecorino/INTRO_TEXT/Chapter%203%20Religion/Ontological.htm#ROBERT%20FLINT)

---

View also [Debunking the Teleological](http://www.youtube.com/watch?v=iRulK_ePLKM), [Cosmological](http://www.youtube.com/watch?v=iRulK_ePLKM), and [Ontological Arguments for the Existence of God](http://www.youtube.com/watch?v=iRulK_ePLKM)

[Read the critiques of the Ontological Argument](http://www.fordham.edu/halsall/basis/anselm-critics.html)

---

### Concluding Summary:

1. What it does prove:
  (a) Anselm proves that if you think of the GCB you must THINK that it exists.
  (b) Descartes proves that if you conceive of an ALL PERFECT being you must CONCEIVE (THINK) of that being as existing.


2. Kant points out that even though you must THINK that it exists does not mean that it does exist. Existence is not something we can know from the mere idea itself. It is not known as a predicate of a subject. Independent confirmation through experience is needed.

3. The argument does give some support to those who are already believers. It has variations that establish the possibility of the existence of such a being.

4. The argument will not convert the non-believer into a believer.

---

### Outcome Assessment

This argument or proof does not establish the actual existence of a supernatural deity. It attempts to define a being into existence and that is not rationally legitimate. While the argument can not be used to convert a non-believer to a believer, the faults in the argument do not prove that there is no god. The Burden of Proof demands that the positive claim that there is a supernatural deity be established by reason and evidence and this argument does not meet that standard. The believer in god can use the argument to establish the mere logical possibility that there is a supernatural deity or at least that it is not irrational to believe in the possibility that there is such a being. The argument does not establish any degree of probability at all.

---

OUTCOME:

The Argument:

Premises

* Suppose (S) that the greatest conceivable being (GCB) exists in the mind alone and not in reality(gcb1).
* Then the greatest conceivable being would not be the greatest conceivable being because one could think of a being like (gcb1) but think of the gcb as existing in reality (gcb2) and not just in the mind.
* So, gcb1 would not be the GCB but gcb2 would be.
* Thus to think of the GCB is to think of the gcb2, i.e. a being that exists in reality and not just in the mind.

---

### Conclusion: The GCB ( Deity) exists

Problem with argument:

1. ____Premises are false

2. ____Premises are irrelevant

3. ____Premises Contain the Conclusion –Circular Reasoning

4. __X__Premises are inadequate to support the conclusion

5. ____Alternative arguments exist with equal or greater support

---

* This argument or proof has flaws in it and would not convince a rational person to accept its conclusion.
* This is not because someone who does not believe in a deity will simply refuse to accept based on emotions or past history but because it is not rationally compelling of acceptance of its conclusion.

---

It would be a mistake in thinking, a violation of logic and a fallacy to think that because this argument or attempt to prove that there is a deity of some type does not work or has flaws that the opposite conclusion must be true, namely that there is no deity of any type.  The error is known as the fallacy "argumentum ad ignoratio" or the appeal to ignorance. It is the mistake in thinking that if an argument cannot prove a proposition or claim P is true then P must be false.  OR if you cannot prove that P is false then P must be true.  It is a mistake to think that way., a logical error.

Proceed to the next section.

Creative Commons License
Introduction to Philosophy by Philip A. Pecorino is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
Return to:               Table of Contents for the Online Textbook

