---
title: Philosophy of Law
---

## Course Objectives

In general, philosophy requires one to apply principles of reasoning to different philosophical issues. Accordingly, one of my goals in this course is to help you improve your critical reasoning skills. These skills are useful not only with respect to this class, but to other philosophy and law classes as well. A second goal of mine is to teach you some of the fundamental philosophical ideas behind much of that which we call law. We will examine theories which attempt to provide answers to such questions as: What is a law? What makes a law valid or binding? Does one always have a moral obligation to obey the law? What gives society the right to punish people whose actions are harmful only to the individual, him/herself (paternalism)? Does society have the right to harm those who break the law (criminal punishment)? Should attempted crimes be punished less severely than completed crimes? We will not spend much time discussing specific public policy issues such as: Whether raising the drinking age saves lives, whether smoking marijuana is a victimless crime (whether it harms others), or whether the death penalty is a deterrent. We will not discuss what the law is; instead, we will discuss what the law ought to be.

### Syllabus (Subject to Modification)

### CLASS DISCUSSION SCHEDULE:

Tuesday, January 16. Introduction to Philosophy of Law and Organization of Class \
Thursday, January 18. Fuller, "The Case of the Spelunkean Explorers" (Handout - Canvas) \
Tuesday, January 23. Kretzmann, “Lex Iniusta Non Est Lex: Laws on Trial” (Handout – Canvas) \
Thursday, January 25. Bentham, “The Principles of Morals and Legislation” (Handout – D2L) \
Tuesday, January 30. Bentham (Continued) \
Thursday, February 1. Hart, “Law as the Union of Primary and Secondary Rules” (crc, 53) \
Tuesday, February 6. Hart, (Continued) \
Thursday, February 8. Dworkin, “The Model of Rules” (148) \
Tuesday, February 13. Dworkin, “Integrity in Law” (169) \
Thursday, February 15. Holmes, “The Path of the Law” (197); Frank, “Legal Realism” (205); \
Tuesday, February 20. Critical Legal Studies (Handout – D2L) \
Thursday, February 22. Plato, Crito, (Handout – D2L) \
Tuesday, February 27. Crito, (Continued) \
Thursday, March 1. Wrap-up Part 1 \
Tuesday, March 6. Examination 1 \
Thursday, March 8. Hart, “Postscript: Responsibility and Retribution” (317) \
Tuesday, March 13. Duff, “Choice, Character, and Action” (328) \
Thursday, March 15. Parker, “Blame, Punishment and the Role of Result” (Handout – D2L) \
Tuesday, March 20. Spring Break \
Thursday, March 22. Spring Break. \
Tuesday, March 27. Self Defense (Handout – D2L) \
Thursday, March 29. Self Defense (Continued) \
Tuesday, April 3. Excuse, Justification, Subjective/Objective Liability (Handout – D2L) \
Thursday, April 5. Mill. “On Liberty” (258). \
Tuesday, April 10. Dworkin, “Paternalism” (271); Griswold v. Connecticut (summary on www) \
Thursday, April 12. Devlin, “Morals and the Criminal Law” (283) \
Tuesday, April 17. “The Moral Significance of Terrorism” (Handout – D2l) \
Thursday, April 19 Dershowitz, “Should the Ticking Bomb Terrorist be Tortured” (Paper Due at End of Class) \
Tuesday, April 24. Bork, “The Original Understanding” (Handout – D2L) \
Thursday, April 26. Bork (Continued) \
Tuesday, May 1. TBD – Student Input Requested \
Thursday, May 3. Wrap-Up and Review

### Evaluated Activities:

Grades will be based on the following scale:

A = 360 and above \
B = 320-359 \
C = 280-319 \
D = 240-279 \
F = 239 and below

Four primary factors will go into determining your grade:

|||
|---|---|
| Quizzes	|	100 points |
| Paper	|	100 points |
| Examination One	|	100 points |
| Final Examination	|	100 points |
