# Crito

In the Crito, Socrates is awaiting his execution in an Athenian prison on charges of impiety against the recognized Athenian gods, and corrupting the youth of Athens. For his punishment, Socrates will forced to commit suicide by drinking the deadly poison hemlock.

> “No, it hasn't arrived, but it looks like it will arrive today, based on the report of some people who have come from Sounion\* and who left when it was there. It's clear from this that it will arrive today, and you will have to end your life tomorrow, Socrates.” ([Woods and Pack, 2022, p. 1](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=3&annotation=83YTGSEI))

Crito, a prominent Athenian citizen has entered Socrates' cell while Socrates was still asleep. As Socrates begins to awaken, Crito states the purpose of his visit. This purpose goes beyond a mere visit as one who will soon need to bid farewell to a trusted and deeply loved friend, and begins to implore Socrates to escape Athens.

Some Reasons for escape include:

| | |
|---|---|
| Eternal Separation from Friends and Family | |
| Friends will be accused of being unfaithful | Accused by whom? |
| Betraying Family, prioritizing Athenian laws over and above family: Betrayal | |
| Satisfying the desires of his enemies | |
| The trial and conviction were utterly unnecessary | |

## Betrayal By Friends

> “If you die, for me it won't be just one misfortune: apart from being separated from the kind of friend the like of which I will never find again, many people, moreover, who do not know me and you well will think that I could have saved you if I were willing to spend the money, but that I didn't care to. And wouldn't this indeed be the most shameful reputation, that I would seem to value money above friends? For the many will not believe that it was you yourself who refused to leave here, even though we were urging you to.” ([Woods and Pack, 2022, p. 2](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=4&annotation=Q2LNUMTE))
